package main

import (
	"context"
	"fmt"
	"go-polls-service/internal/core/core_logger"
	"go-polls-service/internal/core/http_server"
	"go-polls-service/internal/core_middleware"
	"go-polls-service/internal/handler"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	_ "go-polls-service/docs" // docs are generated by Swag CLI

	"github.com/labstack/echo/v4"
	"go.uber.org/zap"
)

func main() {
	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	logger, err := core_logger.NewLogger(core_logger.NewConfigMust())
	if err != nil {
		fmt.Println("Failed to create core_logger:", err)
		os.Exit(1)
	}
	defer logger.Close()

	logger.Debug("Starting Polls Service")

	usersTransportHTTP := handler.NewUsersHTTPHandler(nil)
	usersRoutes := usersTransportHTTP.Routes()

	apiVersionRouter := http_server.NewAPIVersionRouter(http_server.ApiVersion1)
	apiVersionRouter.RegisterRoutes(usersRoutes...)

	httpServer := http_server.NewHTTPServer(
		http_server.NewConfigMust(),
		logger,
		core_middleware.RequestID(),
		core_middleware.Logger(logger),
		core_middleware.Panic(),
		core_middleware.Trace(),
	)

	httpServer.RegisterAPIRouters(apiVersionRouter)

	if err := httpServer.Run(ctx); err != nil {
		logger.Error("HTTP server start error", zap.Error(err))
	}
}

// HealthCheck godoc
//
//	@Summary		health check
//	@Description	Returns service health status
//	@Tags			health
//	@Produce		JSON
//	@Success		200	{object}	map[string]string
//	@Router			/health [get]
func HealthCheck(c echo.Context) error {
	return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
}
