package main

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "go-polls-service/docs" // docs are generated by Swag CLI
)

//	@title			Polls Service API
//	@version		1.0
//	@description	This is a polls service API server.
//	@host			localhost:8080
//	@BasePath		/api/v1
//	@schemes		http
func main() {
	e := echo.New()
	e.HideBanner = true

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Swagger UI: http://localhost:8080/swagger/index.html
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	// Health check
	e.GET("/api/v1/health", HealthCheck)

	fmt.Println("🚀 Polls Service started")
	fmt.Println("📖 Swagger UI: http://localhost:8080/swagger/index.html")
	fmt.Println("💚 Health: http://localhost:8080/api/v1/health")
	e.Logger.Fatal(e.Start(":8080"))
}

// HealthCheck godoc
//
//	@Summary		health check
//	@Description	Returns service health status
//	@Tags			health
//	@Produce		JSON
//	@Success		200	{object}	map[string]string
//	@Router			/health [get]
func HealthCheck(c echo.Context) error {
	return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
}
